version: '3.0'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web_prod
    links:
      - web_prod:web_prod
    volumes:
      - static_volume:/usr/src/juntossomosmais/api/static
    networks:
      - nginx_network

  web_prod:
    container_name: web_prod
    build: ./api/
    command: sh -c "gunicorn api.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/usr/src/juntossomosmais/api
      - static_volume:/usr/src/juntossomosmais/api/static
    env_file:
      - prod.env
    networks:
      - nginx_network

volumes:
  static_volume:

networks:
  nginx_network:
    driver: bridge