version: '3.0'
services:
  web:
    container_name: web
    build: ./api/
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/usr/src/juntossomosmais/api
    env_file:
      - .env